project:
  type: website

website:
  title: "Thomas Vroylandt"
  search: false
  sidebar:
    style: "docked"
    pinned: false
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/thomas-vroylandt-9a2334190/?originalSubdomain=fr
      - icon: github
        href: https://github.com/tvroylandt

format:
  html:
    theme: journal
    mainfont: "sans-serif"
    css: styles.scss
    toc: true

execute:
  freeze: auto

