project:
  type: website

website:
  title: "Thomas Vroylandt"
  search: false
  sidebar:
    style: "docked"
    pinned: false
    contents:
      - about.qmd
      - articles.qmd
      - clients.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/thomas-vroylandt-9a2334190/?originalSubdomain=fr
      - icon: github
        href: https://github.com/tvroylandt
    left: 


format:
  html:
    theme: journal
    mainfont: "Lexend"
    css: styles.scss
    toc: true

execute:
  freeze: auto

