project:
  type: website

website:
  title: "Thomas Vroylandt"
  navbar:
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/thomas-vroylandt-9a2334190/?originalSubdomain=fr
      - icon: github
        href: https://github.com/tvroylandt

format:
  html:
    theme: sandstone
    mainfont: "Figtree"
    css: styles.css
    toc: true

execute:
  freeze: auto

