project:
  type: website

website:
  title: "Thomas Vroylandt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    mainfont: "Figtree"
    css: styles.css
    toc: true

execute:
  freeze: auto

