---
title: "Articles"

listing:
  categories: true
  sort: "date desc"
  type: grid
  page-size: 9

  contents:
    - "articles/"
    - path: https://pagedreport.rfortherestofus.com/
      title: "`pagedreport`"
      description: "`pagedreport` is an R package to help you make beautiful PDF-based reports from RMarkdown"
      date: "2021-05-01"
      categories: [Reports, RMarkdown, Templates]
    - path: https://github.com/kantiles/quarto.report/
      title: "`quarto.report`"
      description: "`quarto.report` is a Quarto extension to help you create reports in Quarto without the burden of handling the stylesheet"
      date: "2024-07-09"
      categories: [Reports, Quarto, Templates]

---

Projects I was involved in.

_Talks_

RR2021 pagedown https://www.youtube.com/watch?v=Vk5q_pvp1EE + https://github.com/tvroylandt/pagedown_rr2021
RR2021 gouvdown https://www.youtube.com/watch?v=18_XWzG6KdM + https://github.com/tvroylandt/gouvdown_rr_2021
RR2024 https://github.com/tvroylandt/rr_2024
Meetup R Addicts retour RR 2024 https://github.com/tvroylandt/rr_2024_retour
UseR 2024 https://github.com/tvroylandt/user_2024_parametrized_reporting

_Blog posts_

Reprendre les posts Tillac

_Conseil - Drees_

- Panorama statistique : https://data.drees.solidarites-sante.gouv.fr/explore/?q=PANORAMA+STATISTIQUE&sort=modified

- ISD : https://drees.solidarites-sante.gouv.fr/240528_DATA_ISD

_Conseil - R for the Rest of Us_ --> en marquer certains en draft ?

CT data : https://www.ctdata.org/blog/2020-psc-housing-data-profiles + https://housingprofiles.pschousing.org/

IA2030 : https://publichealth.jhu.edu/ivac/2024/new-ia2030-country-profiles-to-track-immunization-achievements /+ https://scorecard.immunizationagenda2030.org/pdfs/afg.pdf

OHDC Farmworker Assessment Needs : https://www.ohdc.org/uploads/1/1/2/4/11243168/ohdc_farmworker_needs_assessment_2022.pdf

Oregon by the Numbers : https://www.tfff.org/oregon-numbers/

Oregon Voices : https://www.orvoices.org/your-county/

OMNI : https://github.com/rfortherestofus/omni

ORS Impact : https://funderscommittee.org/2020censusstatereports/

IVAC Pneumonia : https://publichealth.jhu.edu/ivac/resources/pneumonia-diarrhea-progress-reports

CBEM Judi's House : https://judishouse.org/research-tools/cbem/cbem-key-topics/cbem-race-ethnicity/cbem-race-ethnicity-reports/

MPSI PAX template for Crystal : https://github.com/rfortherestofus/mpsi-pax/tree/main

The Mark : https://github.com/rfortherestofus/themark?tab=readme-ov-file

Sustain East Africa

PMP : https://prosperportland.us/

Torch : https://github.com/rfortherestofus/torch-leadership-reports + custom course

Reading Partners : https://github.com/rfortherestofus/rpdashboard

PP covid relief : https://github.com/rfortherestofus/pp-covid-biz-relief

MPSI Covid reports : https://github.com/rfortherestofus/mpsi-covid-reports/tree/master

Unicef Covid : https://github.com/rfortherestofus/unicef-covid

CWP 

CSEAP

Pubs Effect

Some project like NOAA Fisheries 

Internal API : Muse, Statamic, ConvertKit, ...

_Conseil - autres_

Propre
gouvdown https://github.com/spyrales/gouvdown

_Formations_

ICP : https://github.com/tvroylandt/icp_techniques_quanti_2019

https://tvroylandt.github.io/r-cartostat/
https://github.com/tvroylandt/r-graph?tab=readme-ov-file

Pagedown course

_Unédic_

https://www.unedic.org/publications/comprendre-le-sous-emploi

https://www.unedic.org/publications/effets-de-ladaptation-des-regles-dassurance-chomage-la-conjoncture

https://www.unedic.org/publications/suivi-et-effets-de-la-reglementation-d-assurance-chomage-en-2023

https://www.unedic.org/publications/suivi-de-la-reglementation-2021-d-assurance-chomage

https://www.unedic.org/publications/assurance-chomage-et-minima-sociaux-panorama-des-dispositifs

https://www.unedic.org/publications/comment-s-articulent-chomage-prime-d-activite-et-rsa


_Pôle emploi_

Tensions : https://dares.travail-emploi.gouv.fr/publications/les-tensions-sur-le-marche-du-travail-en-2019

VPPEC Sport : https://www.strategie.gouv.fr/sites/strategie.gouv.fr/files/atoms/files/fs-2019-rapport-vppec-sport-fevrier-2019.pdf

Compétences : https://statistiques.francetravail.org/offres/offrespub/201566

BMO : https://statistiques.francetravail.org/bmo/bmopub/209090

https://statistiques.francetravail.org/bmo/bmopub/207249

https://statistiques.francetravail.org/bmo/bmopub/207884

BMO Flash : https://statistiques.francetravail.org/offres/offrespub/206736

Offres emploi : https://www.francetravail.org/files/live/sites/peorg/files/documents/Statistiques-et-analyses/S%26I/SI_18.006.pdf

https://statistiques.francetravail.org/offres/offrespub/207732

https://statistiques.francetravail.org/offres/offrespub/199728

Intérim : https://www.francetravail.org/files/live/sites/peorg/files/documents/Statistiques-et-analyses/S%26I/si_19.014_interim_2019janv.pdf

Métiers : https://www.francetravail.org/statistiques-analyses/entreprises/metiers/tableau-de-la-filiere-maritime-et-fluviale-en-france.html?type=article



_Drees_

https://drees.solidarites-sante.gouv.fr/publications/etudes-et-resultats/les-assistantes-maternelles-ont-gagne-en-moyenne-1-108-euros-en

https://drees.solidarites-sante.gouv.fr/publications/etudes-et-resultats/une-baisse-de-7-des-etudiants-inscrits-en-formations-sociales

https://drees.solidarites-sante.gouv.fr/publications/etudes-et-resultats/les-assistantes-maternelles-gardent-8-denfants-de-plus-en-2014

https://drees.solidarites-sante.gouv.fr/publications/etudes-et-resultats/7-800-etudiants-en-formation-dassistant-de-service-social-en-2016

https://drees.solidarites-sante.gouv.fr/publications/etudes-et-resultats/formations-en-travail-social-62-000-etudiants-en-2014

https://drees.solidarites-sante.gouv.fr/publications/etudes-et-resultats/115-000-personnes-travaillent-en-2016-dans-le-secteur-de-laction

https://drees.solidarites-sante.gouv.fr/publications/les-dossiers-de-la-drees/des-conditions-de-travail-en-ehpad-vecues-comme-difficiles

_Articles_

https://www.cairn.info/revue-savoir-agir-2015-3-page-103.htm

https://www.cairn.info/revue-participations-2017-3-page-49.htm

_Journée d'études_

Vroylandt (Th.), « Ethnographie, numérique et statistiques : les Veilleurs de la “Manif pour tous” », Journée d’études « De la constitution d’un corpus aux analyses statistiques », Paris, Université de Nanterre, 10 octobre 2016.

_Comptes-rendus de publications_

https://journals.openedition.org/lectures/13204
https://www.nonfiction.fr/fiche-perso-1783-thomas-vroylandt.htm

_Scoutisme_

https://www.associations.gouv.fr/IMG/pdf/rapport_final_etude_fdva.pdf

https://www.youtube.com/watch?v=BpW2_Gvs2Ds
https://github.com/tvroylandt/sgdf_pagedown

https://github.com/tvroylandt/intuthu

Autres projets publics ?
